import { Injectable } from '@angular/core';
import { Account } from '../models/account.model';

@Injectable({
  providedIn: 'root',
})
export class BankService {
  private accounts: Account[] = [
    {
      id: 1,
      accountName: 'บัญชีออมทรัพย์',
      accountNumber: '1234-5678-9012',
      balance: 1000,
      openingDate: new Date('2023-01-15'),
      accountType: 'ออมทรัพย์',
      accountStatus: 'ใช้งาน',
      branch: 'สาขากรุงเทพ',
      interestRate: 0.5,
      currency: 'THB',
      ownerName: 'นายสมชาย ใจดี',
      ownerAddress: '123 ถนนสุขสบาย กรุงเทพฯ',
      ownerPhone: '081-234-5678',
      ownerEmail: 'somchai@example.com',
      accountManager: 'นางสาวสมหญิง ใจดี',
      lastTransactionDate: new Date('2023-12-01'),
      accountPurpose: 'ออมเงิน',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารกรุงเทพ',
    },
    {
      id: 2,
      accountName: 'บัญชีเดินสะพัด',
      accountNumber: '9876-5432-1098',
      balance: 5000,
      openingDate: new Date('2023-03-20'),
      accountType: 'เดินสะพัด',
      accountStatus: 'ใช้งาน',
      branch: 'สาขาชลบุรี',
      interestRate: 0.2,
      currency: 'THB',
      ownerName: 'นางสาวสมหญิง ใจดี',
      ownerAddress: '456 ถนนสุขสบาย ชลบุรี',
      ownerPhone: '082-345-6789',
      ownerEmail: 'somying@example.com',
      accountManager: 'นายสมชาย ใจดี',
      lastTransactionDate: new Date('2023-12-02'),
      accountPurpose: 'ใช้จ่ายประจำวัน',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารกสิกรไทย',
    },
    {
      id: 3,
      accountName: 'บัญชีเงินฝากประจำ',
      accountNumber: '5678-9012-3456',
      balance: 10000,
      openingDate: new Date('2023-05-10'),
      accountType: 'เงินฝากประจำ',
      accountStatus: 'ใช้งาน',
      branch: 'สาขาภูเก็ต',
      interestRate: 1.0,
      currency: 'THB',
      ownerName: 'นายสมชาย ใจดี',
      ownerAddress: '789 ถนนสุขสบาย ภูเก็ต',
      ownerPhone: '083-456-7890',
      ownerEmail: 'somchai@example.com',
      accountManager: 'นางสาวสมหญิง ใจดี',
      lastTransactionDate: new Date('2023-12-03'),
      accountPurpose: 'เงินฝากประจำ',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารกรุงไทย',
    },
    {
      id: 4,
      accountName: 'บัญชีออมทรัพย์พิเศษ',
      accountNumber: '6789-0123-4567',
      balance: 2000,
      openingDate: new Date('2023-06-15'),
      accountType: 'ออมทรัพย์',
      accountStatus: 'ใช้งาน',
      branch: 'สาขาเชียงใหม่',
      interestRate: 0.7,
      currency: 'THB',
      ownerName: 'นางสาวสมใจ หวังดี',
      ownerAddress: '101 ถนนสุขสบาย เชียงใหม่',
      ownerPhone: '084-567-8901',
      ownerEmail: 'somjai@example.com',
      accountManager: 'นายสมชาย ใจดี',
      lastTransactionDate: new Date('2023-12-04'),
      accountPurpose: 'ออมเงินระยะสั้น',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารทหารไทย',
    },
    {
      id: 5,
      accountName: 'บัญชีเดินสะพัดธุรกิจ',
      accountNumber: '0123-4567-8901',
      balance: 15000,
      openingDate: new Date('2023-08-01'),
      accountType: 'เดินสะพัด',
      accountStatus: 'ใช้งาน',
      branch: 'สาขาหาดใหญ่',
      interestRate: 0.3,
      currency: 'THB',
      ownerName: 'บริษัท สบาย จำกัด',
      ownerAddress: '202 ถนนสุขสบาย หาดใหญ่',
      ownerPhone: '085-678-9012',
      ownerEmail: 'info@sabai.com',
      accountManager: 'นางสาวสมหญิง ใจดี',
      lastTransactionDate: new Date('2023-12-05'),
      accountPurpose: 'ใช้จ่ายธุรกิจ',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารไทยพาณิชย์',
    },
    {
      id: 6,
      accountName: 'บัญชีเงินฝากประจำพิเศษ',
      accountNumber: '4567-8901-2345',
      balance: 25000,
      openingDate: new Date('2023-10-15'),
      accountType: 'เงินฝากประจำ',
      accountStatus: 'ใช้งาน',
      branch: 'สาขาอุบลราชธานี',
      interestRate: 1.2,
      currency: 'THB',
      ownerName: 'นายสมหวัง ตั้งใจ',
      ownerAddress: '303 ถนนสุขสบาย อุบลราชธานี',
      ownerPhone: '086-789-0123',
      ownerEmail: 'somwang@example.com',
      accountManager: 'นายสมชาย ใจดี',
      lastTransactionDate: new Date('2023-12-06'),
      accountPurpose: 'เงินฝากประจำระยะยาว',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารกรุงศรีอยุธยา',
    },
    {
      id: 7,
      accountName: 'บัญชีออมทรัพย์สำหรับเด็ก',
      accountNumber: '7890-1234-5678',
      balance: 500,
      openingDate: new Date('2023-11-01'),
      accountType: 'ออมทรัพย์',
      accountStatus: 'ใช้งาน',
      branch: 'สาขาขอนแก่น',
      interestRate: 0.8,
      currency: 'THB',
      ownerName: 'เด็กชายสมบูรณ์ ใจดี',
      ownerAddress: '404 ถนนสุขสบาย ขอนแก่น',
      ownerPhone: '087-890-1234',
      ownerEmail: 'somboon@example.com',
      accountManager: 'นางสาวสมหญิง ใจดี',
      lastTransactionDate: new Date('2023-12-07'),
      accountPurpose: 'ออมเงินสำหรับเด็ก',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารเกียรตินาคิน',
    },
    {
      id: 8,
      accountName: 'บัญชีเดินสะพัดสำหรับธุรกิจขนาดเล็ก',
      accountNumber: '2345-6789-0123',
      balance: 8000,
      openingDate: new Date('2023-09-15'),
      accountType: 'เดินสะพัด',
      accountStatus: 'ใช้งาน',
      branch: 'สาขานครราชสีมา',
      interestRate: 0.4,
      currency: 'THB',
      ownerName: 'ร้านค้าสบายดี',
      ownerAddress: '505 ถนนสุขสบาย นครราชสีมา',
      ownerPhone: '088-901-2345',
      ownerEmail: 'info@sabaidee.com',
      accountManager: 'นายสมชาย ใจดี',
      lastTransactionDate: new Date('2023-12-08'),
      accountPurpose: 'ใช้จ่ายสำหรับธุรกิจขนาดเล็ก',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารซีไอเอ็มบีไทย',
    },
    {
      id: 9,
      accountName: 'บัญชีเงินฝากประจำระยะสั้น',
      accountNumber: '9012-3456-7890',
      balance: 12000,
      openingDate: new Date('2023-07-01'),
      accountType: 'เงินฝากประจำ',
      accountStatus: 'ใช้งาน',
      branch: 'สาขาพิษณุโลก',
      interestRate: 0.9,
      currency: 'THB',
      ownerName: 'นายสมหมาย ตั้งใจ',
      ownerAddress: '606 ถนนสุขสบาย พิษณุโลก',
      ownerPhone: '089-012-3456',
      ownerEmail: 'sommai@example.com',
      accountManager: 'นางสาวสมหญิง ใจดี',
      lastTransactionDate: new Date('2023-12-09'),
      accountPurpose: 'เงินฝากประจำระยะสั้น',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารทิสโก้',
    },
    {
      id: 10,
      accountName: 'บัญชีออมทรัพย์สำหรับผู้สูงอายุ',
      accountNumber: '3456-7890-1234',
      balance: 3000,
      openingDate: new Date('2023-04-15'),
      accountType: 'ออมทรัพย์',
      accountStatus: 'ใช้งาน',
      branch: 'สาขาเชียงราย',
      interestRate: 0.6,
      currency: 'THB',
      ownerName: 'นายสมเกียรติ ยั่งยืน',
      ownerAddress: '707 ถนนสุขสบาย เชียงราย',
      ownerPhone: '090-123-4567',
      ownerEmail: 'somkiat@example.com',
      accountManager: 'นายสมชาย ใจดี',
      lastTransactionDate: new Date('2023-12-10'),
      accountPurpose: 'ออมเงินสำหรับผู้สูงอายุ',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารธนชาต',
    },
    {
      id: 11,
      accountName: 'บัญชีเดินสะพัดสำหรับองค์กร',
      accountNumber: '6789-0123-4567',
      balance: 20000,
      openingDate: new Date('2023-02-01'),
      accountType: 'เดินสะพัด',
      accountStatus: 'ใช้งาน',
      branch: 'สาขาสุราษฎร์ธานี',
      interestRate: 0.5,
      currency: 'THB',
      ownerName: 'บริษัท ยั่งยืน จำกัด',
      ownerAddress: '808 ถนนสุขสบาย สุราษฎร์ธานี',
      ownerPhone: '091-234-5678',
      ownerEmail: 'info@yungyeun.com',
      accountManager: 'นางสาวสมหญิง ใจดี',
      lastTransactionDate: new Date('2023-12-11'),
      accountPurpose: 'ใช้จ่ายสำหรับองค์กร',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารยูโอบี',
    },
    {
      id: 12,
      accountName: 'บัญชีเงินฝากประจำระยะยาว',
      accountNumber: '0123-4567-8901',
      balance: 30000,
      openingDate: new Date('2023-01-01'),
      accountType: 'เงินฝากประจำ',
      accountStatus: 'ใช้งาน',
      branch: 'สาขาตรัง',
      interestRate: 1.1,
      currency: 'THB',
      ownerName: 'นายสมบัติ มั่นคง',
      ownerAddress: '909 ถนนสุขสบาย ตรัง',
      ownerPhone: '092-345-6789',
      ownerEmail: 'sombat@example.com',
      accountManager: 'นายสมชาย ใจดี',
      lastTransactionDate: new Date('2023-12-12'),
      accountPurpose: 'เงินฝากประจำระยะยาว',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารไอซีบีซี (ไทย)',
    },
    {
      id: 13,
      accountName: 'บัญชีออมทรัพย์พิเศษสำหรับนักศึกษา',
      accountNumber: '1122-3344-5566',
      balance: 750,
      openingDate: new Date('2023-11-15'),
      accountType: 'ออมทรัพย์',
      accountStatus: 'ใช้งาน',
      branch: 'สาขาปทุมธานี',
      interestRate: 0.9,
      currency: 'THB',
      ownerName: 'นางสาวสมศรี เรียนดี',
      ownerAddress: '1010 ถนนสุขสบาย ปทุมธานี',
      ownerPhone: '093-456-7890',
      ownerEmail: 'somsri@example.com',
      accountManager: 'นางสาวสมหญิง ใจดี',
      lastTransactionDate: new Date('2023-12-13'),
      accountPurpose: 'ออมเงินสำหรับนักศึกษา',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารกรุงเทพ',
    },
    {
      id: 14,
      accountName: 'บัญชีเดินสะพัดสำหรับบริษัท Startup',
      accountNumber: '4455-6677-8899',
      balance: 18000,
      openingDate: new Date('2023-10-01'),
      accountType: 'เดินสะพัด',
      accountStatus: 'ใช้งาน',
      branch: 'สาขานนทบุรี',
      interestRate: 0.6,
      currency: 'THB',
      ownerName: 'บริษัท ไอเดีย จำกัด',
      ownerAddress: '1111 ถนนสุขสบาย นนทบุรี',
      ownerPhone: '094-567-8901',
      ownerEmail: 'info@idea.com',
      accountManager: 'นายสมชาย ใจดี',
      lastTransactionDate: new Date('2023-12-14'),
      accountPurpose: 'ใช้จ่ายสำหรับบริษัท Startup',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารกรุงศรีอยุธยา',
    },
    {
      id: 15,
      accountName: 'บัญชีเงินฝากประจำสำหรับเกษียณ',
      accountNumber: '7788-9900-1122',
      balance: 40000,
      openingDate: new Date('2023-09-01'),
      accountType: 'เงินฝากประจำ',
      accountStatus: 'ใช้งาน',
      branch: 'สาขาจันทบุรี',
      interestRate: 1.3,
      currency: 'THB',
      ownerName: 'นายสมบูรณ์ เกษมสุข',
      ownerAddress: '1212 ถนนสุขสบาย จันทบุรี',
      ownerPhone: '095-678-9012',
      ownerEmail: 'somboon.k@example.com',
      accountManager: 'นายสมชาย ใจดี',
      lastTransactionDate: new Date('2023-12-15'),
      accountPurpose: 'เงินฝากประจำสำหรับเกษียณ',
      accountNotes: 'ไม่มีหมายเหตุ',
      bankName: 'ธนาคารไทยพาณิชย์',
    },
  ];
  getAccounts(): Account[] {
    return this.accounts;
  }

  getAccount(id: number): Account | undefined {
    return this.accounts.find((account) => account.id === id);
  }

  constructor() { }
}
